docs_dir: docs

# Project information
site_name: IsardVDI
site_url: http://www.isardvdi.com
site_description: IsardVDI Open Source Virtual Desktops.
site_author: IsardVDI

# Repository
repo_name: 'isard-vdi/docs'
repo_url: https://github.com/isard-vdi/docs

# Copyright
copyright: Copyright &copy; 2016 <a href="http://www.isardvdi.com">IsardVDI</a>.

# Documentation and theme
#theme: 'material'
theme:
  name: "readthedocs"
strict: true

# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/john-doe'
    - type: 'twitter'
      link: 'https://twitter.com/john-doe'
    - type: 'linkedin'
      link: 'https://de.linkedin.com/in/john-doe'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# TOC
pages:
- Introduction: index.md
- Installation:
    - docker-compose: install/docker-compose.md
    - First Steps: install/first-steps.md
    - certificates: install/certificates.md
- User:
    - Desktops: user/desktops.md
    - Templates: user/templates.md
    - Media: user/media.md
    - Quotas: user/quotas.md
    - Allows: user/allows.md
- Admin:
    - Users: admin/users.md
    - Domains: 
        - Desktops: admin/domains/desktops.md
        - Templates: admin/domains/templates.md
        - Bases: admin/domains/bases.md
        - Media: admin/domains/media.md
        - Resources: admin/domains/resources.md
    - Hypervisors: admin/hypervisors.md
    - Updates: admin/updates.md
    - FAQ: admin/faq.md
- About: about.md

